apiVersion: batch/v1
kind: Job
metadata:
  name: myjob
spec:
  # activeDeadlineSeconds: 30
  # backoffLimit: 4
  # parallelism: 2
  # completions: 5
  template:
    metadata:
      name: job-pod
      labels:
        app: myapp
    spec:
      containers:
      - name: myjob-container
        image: busybox
        command: ['sleep', '60']
      restartPolicy: Never